# Generated by Django 4.2.1 on 2023-05-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.FloatField(max_length=5)),
                ('sepal_width', models.FloatField(max_length=5)),
                ('petal_length', models.FloatField(max_length=5)),
                ('petal_width', models.FloatField(max_length=5)),
                ('species_id', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_id', models.IntegerField(max_length=5)),
                ('species', models.CharField(max_length=100)),
            ],
        ),
    ]
