# Generated by Django 4.2.1 on 2023-05-22 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='species_id',
        ),
        migrations.RemoveField(
            model_name='species',
            name='species_id',
        ),
    ]
