# Generated by Django 4.2.1 on 2023-05-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_remove_observation_species_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'managed': False},
        ),
    ]
