# Generated by Django 4.2.1 on 2023-05-24 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_observation_options_alter_species_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='observation',
            table='Observation',
        ),
        migrations.AlterModelTable(
            name='species',
            table='Species',
        ),
    ]
